### ISSUE TITLE
[Bug]: crash within `mypy` on `sympy/polys/numberfields/resolvent_lookup.py`

### ISSUE THREAD

**Issue by jamesbraza** [dosisod/refurb#302]
### Has your issue already been fixed?

- [X] Have you checked to see if your issue still exists on the `master` branch? See [the docs](https://github.com/dosisod/refurb#developing) for instructions on how to setup a local build of Refurb.
- [X] Have you looked at the open/closed issues to see if anyone has already reported your issue?

### The Bug

I have `sympy==1.12` installed as it's a dependency of `torch==2.1.0`.  Running `refurb` on some files:

```bash
> refurb dir1 file.py
/usr/local/lib/python3.11/site-packages/sympy/polys/numberfields/resolvent_lookup.py: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
If this issue continues with mypy master, please report a bug at https://github.com/python/mypy/issues
version: 1.6.1
/usr/local/lib/python3.11/site-packages/sympy/polys/numberfields/resolvent_lookup.py: : note: please use --show-traceback to print a traceback when reporting a bug
```

Running `mypy` on the same files does not have this error. I want to use `--show-traceback` so I can properly debug this issue (perhaps report the crash to `mypy`).

Here is some more info on the Docker container:

```bash
> uname -a
Linux 26cbe3fc0bf0 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 GNU/Linux
> dpkg --print-architecture
arm64
```

### Version Info

```shell
Refurb: v1.22.1
Mypy: v1.6.1
```

### Python Version

3.11.5

### Config File

```TOML
[tool.mypy]
check_untyped_defs = true
error_summary = false
platform = "linux"
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
warn_redundant_casts = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
ignore_missing_imports = true
module = [
    "fastapi_socketio",  # SEE: https://github.com/pyropy/fastapi-socketio/issues/27
    "fsspec",  # SEE: https://github.com/fsspec/filesystem_spec/issues/625
    "huggingface_hub",  # SEE: https://github.com/huggingface/huggingface_hub/issues/1662
    "rapidjson",  # SEE: https://github.com/python-rapidjson/python-rapidjson/issues/190
    "s3fs",  # SEE: https://github.com/fsspec/s3fs/issues/383
    "setuptools_scm",  # SEE: https://github.com/pypa/setuptools_scm/issues/501
    "socketio.*",  # SEE: https://github.com/miguelgrinberg/python-socketio/issues/1276
    "streamlit_pydantic",
    "transformers",
]

[tool.refurb]
enable_all = true
ignore = [
    "FURB103",
    "FURB141",
    "FURB144",
    "FURB147",
    "FURB150",
    "FURB155",
]
```

### Extra Info

Here is the relevant `sympy` file: [`resolvent_lookup.py`](https://github.com/sympy/sympy/blob/sympy-1.12/sympy/polys/numberfields/resolvent_lookup.py)

Running `mypy` on the file directly:

```bash
> touch a.py
> # Copy resolvent_lookup.py into a.py
> mypy a.py
```

It doesn't seem to crash or have an error, I am not sure.  Trying the current head of `sympy`:

```bash
> pip install git+https://github.com/sympy/sympy.git
...
Successfully installed sympy-1.13.dev0
> refurb dir1 file.py
# Same error as above
```
